LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := GDialer
LOCAL_OVERRIDES_PACKAGES := Dialer
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Gdialer.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_PRODUCT_MODULE := true
include $(BUILD_PREBUILT)
